version: '3.9'
services:

  db:
    container_name: database
    restart: unless-stopped
    image: postgres:14
    ports:
      - '5432:5432'
    env_file:
      - ./database/.env
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis/d–∞ta:/usr/local/redis/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - ./redis/.env

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: unless-stopped
    volumes:
      - ./server/xml:/xml
    ports:
      - '8080:8080'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local