version: '3.9'
services:

  db:
    container_name: database
    restart: unless-stopped
    image: postgres:14
    ports:
      - '5432:5432'
    env_file:
      - ./database/.env
    volumes:
      - 'dbdata:/var/lib/postgresql/data'
    networks:
      - api

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local