version: '3.9'
services:

  db:
    container_name: database
    restart: unless-stopped
    image: postgres:14
    ports:
      - '5432:5432'
    env_file:
      - ./database/.env
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/usr/local/redis/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - ./redis/.env
    networks:
      - app-network
    command:
      redis-server /usr/local/etc/redis/redis.conf --requirepass password


  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: unless-stopped
    volumes:
      - ./server/xml:/xml
    ports:
      - '8080:8080'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redisdata:
    driver: local
  dbdata:
    driver: local